name: Extension Build & Publish to Firefox & Github

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get version from package.json
        id: version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:firefox

      - name: Zip Firefox Extension
        run: cd build && zip -r ../looi-extension.zip . && cd

      - name: Upload extension zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: looi-extension
          path: looi-extension.zip

  publish_firefox:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download firefox zip
        uses: actions/download-artifact@v4
        with:
          name: looi-extension
      - name: Publish to Firefox Add-ons
        uses: cardinalby/webext-buildtools-firefox-addons-action@v1
        with:
          zipFilePath: looi-extension.zip
          extensionId: ${{ secrets.FF_EXTENSION_ID }}
          jwtIssuer: ${{ secrets.FF_JWT_ISSUER }}
          jwtSecret: ${{ secrets.FF_JWT_SECRET }}

  github_release:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download Looi Extension zip
        uses: actions/download-artifact@v4
        with:
          name: looi-extension

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: looi-extension.zip
          name: Looi-${VERSION}
          tag_name: ${VERSION}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
