name: Build & Release Extensions

on:
    push:
        branches:
            - release

jobs:
    release:
        name: Build and publish release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Get version from package.json
              id: version
              run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

            - name: Install dependencies
              run: npm ci

            - name: Build Chrome extension
              run: |
                  npm run build:chrome
                  mkdir -p release/chrome
                  cp -r build/* release/chrome/
                  cd release/chrome && zip -r ../chrome-extension.zip .

            - name: Build Firefox extension
              run: |
                  npm run build:firefox
                  mkdir -p release/firefox
                  cp -r build/* release/firefox/
                  cd release/firefox && zip -r ../firefox-extension.zip .

            - name: Create GitHub Release
              id: create_release
              uses: softprops/action-gh-release@v2
              with:
                  name: Looi-${{ env.VERSION }}
                  tag_name: ${{ env.VERSION }}
                  body_path: CHANGELOG.md
                  draft: false
                  prerelease: false
                  files: |
                      release/chrome-extension.zip
                      release/firefox-extension.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
